name: iqbal_literature
description: A comprehensive collection of Dr. Allama Iqbal's literary works featuring AI-powered analysis, advanced search, and beautiful typography.
publish_to: 'none'
version: 1.1.0+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # Database and Storage
  sqflite: ^2.3.0
  path: ^1.8.3
 
  path_provider: ^2.1.1

  # Firebase
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_analytics: ^11.5.0
  firebase_auth: ^5.6.0
  firebase_crashlytics: ^4.3.7
  firebase_performance: ^0.10.1+7
  firebase_storage: ^12.4.7

  # UI Components
  flutter_native_splash: ^2.3.8
  device_preview: ^1.1.0
  flutter_screenutil: ^5.9.0
  flutter_displaymode: ^0.6.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.17
  flutter_markdown: ^0.6.18+2
  shimmer: ^3.0.0

  # Utils
  package_info_plus: ^8.3.0
  intl: ^0.20.2
  url_launcher: ^6.1.14
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.2
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.2
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  

  # Icons
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.0
  timeline_tile: ^2.0.0
  animated_text_kit: ^4.2.2
  hovering: ^1.0.4  # Update this line
  pdf: ^3.11.3
  image: ^4.1.3
  # No speech_to_text dependency

  # AI
  google_generative_ai: ^0.2.0
  syncfusion_flutter_pdf: ^24.1.46

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.14
  hive_generator: ^2.0.1
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.25.8
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/database/data.db
    - assets/fonts/
    - assets/fonts/JameelNooriNastaleeq.ttf
    - assets/fonts/Jameel-Noori-Nastaleeq-Regular.ttf
    - assets/fonts/MehrNastaliq-Regular.ttf
    - assets/fonts/NotoNastaliqUrdu-Regular.ttf
    - assets/images/notebook_lines.png
    - assets/icon/
    - assets/images/backgrounds/

  
  fonts:
    - family: JameelNooriNastaleeq
      fonts:
        - asset: assets/fonts/JameelNooriNastaleeq.ttf
        - asset: assets/fonts/Jameel-Noori-Nastaleeq-Regular.ttf

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/iqbalApp_logo.png
  color_dark: "#121212"
  image_dark: assets/icon/iqbalApp_logo.png
  android: true
  ios: true
  web: false
  android_12:
    image: assets/icon/iqbalApp_logo.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/icon/iqbalApp_logo.png
    icon_background_color_dark: "#121212"
  fullscreen: true
  android_gravity: center
  ios_content_mode: center

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/iqbalApp_logo.png"
  
  # Android adaptive icons (round on modern Android)
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/iqbalApp_logo.png"
  
  # Web configuration
  web:
    generate: true
    image_path: "assets/icon/iqbalApp_logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"




